// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20190511213227_BankNombre")]
    partial class BankNombre
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Models.BankEntity", b =>
                {
                    b.Property<int>("BankEntityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodPostal");

                    b.Property<string>("Direccion");

                    b.Property<bool>("Estado_Activo");

                    b.Property<int?>("GroupEntityId");

                    b.Property<string>("LogoURL");

                    b.Property<string>("Mail");

                    b.Property<string>("Nombre");

                    b.Property<string>("Pais");

                    b.Property<string>("Poblacion");

                    b.Property<string>("Provincia");

                    b.Property<string>("Telefono");

                    b.HasKey("BankEntityId");

                    b.HasIndex("GroupEntityId");

                    b.ToTable("BankEntities");
                });

            modelBuilder.Entity("Entities.Models.GroupEntity", b =>
                {
                    b.Property<int>("GroupEntityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color");

                    b.Property<string>("Nombre");

                    b.HasKey("GroupEntityId");

                    b.ToTable("GroupEntities");
                });

            modelBuilder.Entity("Entities.Models.BankEntity", b =>
                {
                    b.HasOne("Entities.Models.GroupEntity", "GroupEntity")
                        .WithMany("BankEntities")
                        .HasForeignKey("GroupEntityId");
                });
#pragma warning restore 612, 618
        }
    }
}
